server:
  port: 7998

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

spring:
  application:
    name: "gateway-service"
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

management:
  endpoints:
    web:
      exposure:
        include: "gateway"
  endpoint:
    gateway:
      enabled: true
