server:
  port: 8004
  forward-headers-strategy: framework

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

spring:
  application:
    name: "order-service"
  data:
    mongodb:
      username: "admin"
      password: "root"
      host: "localhost"
      port: 5004
      database: "order-service"
      authentication-database: "admin"

logging:
  level:
    org:
      springframework:
        data:
          mongodb:
            core:
              MongoTemplate: DEBUG
