server:
  port: 8002
  forward-headers-strategy: framework

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://localhost:8000/eureka

spring:
  application:
    name: "restaurant-service"
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  datasource:
    username: postgres
    password: postgres
    url: "jdbc:postgresql://localhost:5002/restaurant-service"
