INSERT INTO Restaurant (title, address) VALUES ('Restaurant title 1', 'Restaurant address 1');
INSERT INTO Restaurant (title, address) VALUES ('Restaurant title 2', 'Restaurant address 2');
INSERT INTO Restaurant (title, address) VALUES ('Restaurant title 3', 'Restaurant address 3');
INSERT INTO Restaurant (title, address) VALUES ('Restaurant title 4', 'Restaurant address 4');
INSERT INTO Restaurant (title, address) VALUES ('Restaurant title 5', 'Restaurant address 5');
INSERT INTO Restaurant (title, address) VALUES ('Restaurant title 6', 'Restaurant address 6');
INSERT INTO Restaurant (title, address) VALUES ('Restaurant title 7', 'Restaurant address 7');
INSERT INTO Restaurant (title, address) VALUES ('Restaurant title 8', 'Restaurant address 8');

INSERT INTO Product (title, price, restaurant_id) VALUES ('Product title 1', '100', 1);
INSERT INTO Product (title, price, restaurant_id) VALUES ('Product title 2', '200', 1);
INSERT INTO Product (title, price, restaurant_id) VALUES ('Product title 3', '300', 1);
INSERT INTO Product (title, price, restaurant_id) VALUES ('Product title 4', '250', 2);
INSERT INTO Product (title, price, restaurant_id) VALUES ('Product title 5', '70', 3);
INSERT INTO Product (title, price, restaurant_id) VALUES ('Product title 6', '100.5', 3);
INSERT INTO Product (title, price, restaurant_id) VALUES ('Product title 7', '99.99', 3);
INSERT INTO Product (title, price, restaurant_id) VALUES ('Product title 8', '80', 3);
INSERT INTO Product (title, price, restaurant_id) VALUES ('Product title 9', '120', 3);
INSERT INTO Product (title, price, restaurant_id) VALUES ('Product title 10', '1000', 3);
