config:
  server:
    uri: ${CONFIG_SERVER_URI:http://localhost:7999}

spring:
  application:
    name: customer-service
  config:
    import: configserver:${config.server.uri}
  cloud:
    config:
      fail-fast: true
      retry:
        multiplier: 1.5
        max-attempts: 10
        initial-interval: 1000
        max-interval: 5000
